manala:
  template: manala.ansible-role

role:
  name: manala.apt
  description: Handle apt
  tags:
    - system
    - apt
  distributions:
    - debian.jessie
    - debian.stretch
    - raspbian.stretch
